### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by tsumu-github** [tsumu-github/isekaijob#65]
## 各種情報
サービス名　魔法少女:Level0
サービスURL　http://www.magicalgirl-level0.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能

- [ ] Xにてシェア機能

- [ ] 診断をする際の質問内容

- [ ] 診断結果

- ジョブごとのイメージ画像  

- 内容

- 異世界の適正ジョブ

  - ジョブ：騎士

  - 性格、活かされるところ

- 現代の適正ジョブ
  - ジョブ：警察官
  - 結果に基づいた現実世界のキャリアアドバイス
- 結果に基づいたおすすめのリフレッシュ方法

READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください

## READMEレビュー時から変更した機能
開発途中でMVPリリース時点で作らなくなった機能や追加した機能があれば記載してください
なければこの項目は省略してください

- [ ] 診断のテイストを異世界から魔法少女に変更したため、それに合わせて診断結果も変更しました。
- 変更
  - ジョブごとのイメージ画像 　→　魔法少女ごとのイメージ画像
  - 異世界の適正ジョブ　→　心に虹を架ける魔法少女
  - 性格、活かされるところ　→　あなたの特徴・強み
  - 現代の適正ジョブ　→　あなたに向いているかもしれない職業
  - 結果に基づいた現実世界のキャリアアドバイス　→　あなたの弱み

- 追加
  - 魔法少女ごとのステータス(★の数)

## サービスイメージがわかるようなスクリーンショット等
特に管理画面など通常ユーザーが触れない機能があったら共有をお願いします

TOP画面
![Image](https://github.com/tsumu-github/isekaijob/assets/138583968/ac7f5e76-87cd-4887-a156-4368f96340cd)

ギルド選択画面
![Image](https://github.com/tsumu-github/isekaijob/assets/138583968/2df61cea-cf11-4e43-91a1-8a774f42805e)

質問画面
![Image](https://github.com/tsumu-github/isekaijob/assets/138583968/3fa3f74e-9e45-4a57-9d7e-77d7a9f981a5)

診断結果画面
![Image](https://github.com/tsumu-github/isekaijob/assets/138583968/dbb41e92-9fa5-4388-90d2-bd3fe4616ef4)

**Comment by tarakish** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
